In [3]:
# 行列演算の基礎

- ベクトルの定義
- 行列の定義
- 転置
- 逆行列
- 行列積

In [4]:
import numpy as np

In [7]:
# ベクトルの定義
x = np.array([[1], [2], [3]])
print(x)

[[1]
 [2]
 [3]]


In [15]:
# 行列の定義
X = np.array([[1,2],[3,4]])
print(X)

[[1 2]
 [3 4]]


In [10]:
# 転置
Xt = X.T
print(Xt)

[[1 3]
 [2 4]]


In [16]:
# 逆行列
X_inv = np.linalg.inv(X)
print(X_inv)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [17]:
# 行列積
XX_inv = np.dot(X, X_inv)
print(XX_inv)

[[1.00000000e+00 1.11022302e-16]
 [0.00000000e+00 1.00000000e+00]]


# よくある間違い

In [19]:
x = np.array([1, 2, 3])
x

array([1, 2, 3])

In [20]:
x.T

array([1, 2, 3])

In [21]:
x = np.array([[1, 2, 3]])
x

array([[1, 2, 3]])

In [22]:
x.T

array([[1],
       [2],
       [3]])

# Numpyでよく使う処理

In [26]:
X = np.array([
    [2, 3, 4],
    [1, 2, 3]
])
print(X)

[[2 3 4]
 [1 2 3]]


In [27]:
X.shape

(2, 3)

In [28]:
row, col = X.shape

In [29]:
row

2

In [30]:
col

3

In [31]:
for x in X:
    print(x)
    print('--')

[2 3 4]
--
[1 2 3]
--


# 演習問題

In [33]:
X = np.array([
    [1, 2, 3],
    [1, 2, 5],
    [1, 3, 4],
    [1, 5 ,9]
])
print(X)

[[1 2 3]
 [1 2 5]
 [1 3 4]
 [1 5 9]]


In [34]:
y = np.array([
    [1],
    [5],
    [6],
    [8]
])
print(y)

[[1]
 [5]
 [6]
 [8]]


In [36]:
# Step1
XtX = np.dot(X.T, X)
print(XtX)

[[  4  12  21]
 [ 12  42  73]
 [ 21  73 131]]


In [38]:
# Step2
XtX_inv = np.linalg.inv(XtX)
print(XtX_inv)

[[ 1.76530612 -0.39795918 -0.06122449]
 [-0.39795918  0.84693878 -0.40816327]
 [-0.06122449 -0.40816327  0.24489796]]


In [39]:
# Step3
Xty = np.dot(X.T, y)
print(Xty)

[[ 20]
 [ 70]
 [124]]


In [40]:
# Step4
w = np.dot(XtX_inv, Xty)
print(w)

[[-0.14285714]
 [ 0.71428571]
 [ 0.57142857]]


# Scikit-learnで実装

In [42]:
# 重回帰分析のみ読み込み
from sklearn.linear_model import LinearRegression

In [47]:
# モデルの宣言
model = LinearRegression(fit_intercept = False)

In [48]:
# モデルの学習　←パラメータの調整を行うこと！
model.fit(X, y)

LinearRegression(copy_X=True, fit_intercept=False, n_jobs=1, normalize=False)

In [49]:
# 調整後のパラメータ
model.coef_

array([[-0.14285714,  0.71428571,  0.57142857]])

In [50]:
model.intercept_

0.0

In [51]:
# 予測精度 ← 決定係数 0だと悪い 1だと良いもの　　　らしい。。。。
model.score(X, y)

0.6923076923076923

In [52]:
# 予測値の計算
x = np.array([[1, 2, 3]])

In [54]:
y_pred = model.predict(x)
y_pred

array([[3.]])